### ISSUE TITLE
help.  where is the demo.py to test my own video and save the 3 d kps to a new video?

### ISSUE THREAD

**Issue by henbucuoshanghai** [3dpose/3D-Multi-Person-Pose#16]

**Comment by 3dpose** [comment]
To run the code on your own video, it is needed to generate p2d, affpts, and affb [(as defined here)](https://github.com/3dpose/3D-Multi-Person-Pose/blob/e6ec9384271ecc4ee70fbd3ba8d9c14ae53f91f8/calculate_mupots_topdown_pts.py#L58), which correspond to joints' location, joints' confidence, and bones' confidence. 
   - For p2d and affpts, any off-the-shelf 2D pose estimators can be used to extract joints' location and their confidence values. 
   - For affb, Part Affinity Field model can be used to extract the bone confidence, [example code is here](https://github.com/spmallick/learnopencv/blob/c4c5336f0bacb7528377638bd62714957a2c24e1/OpenPose-Multi-Person/multi-person-openpose.py#L112). 
   - Note that we use the keypoint definition of H36M dataset, which is compatible with CrowdPose dataset but different from the COCO keypoint definition.

**Comment by henbucuoshanghai** [comment]
tks for kindly help。I get a better model myself about 3d pose .tks
