### ISSUE TITLE
model LICENSE?

### ISSUE THREAD

**Issue by go-to-here** [3dpose/3D-Multi-Person-Pose#3]
Hello! Thank you so much for sharing the code and the model.

I would like to ask, what protocol is the Pre-trained Models? Can I use it in a business project?

Your reply is very much needed.

**Comment by 3dpose** [comment]
The code and the pre-trained models are released under the terms of the [MIT License](https://github.com/3dpose/3D-Multi-Person-Pose/blob/main/LICENSE), so short answer is: yes. It's better to train on your own datasets to for commercial use.
