### ISSUE TITLE
Question about plot the figure 1 in paper

### ISSUE THREAD

**Issue by zenithfang** [3dpose/3D-Multi-Person-Pose#4]
I see figure 1 in paper with a ground grid. Could you tell me how do you get the rotation relationship of people in camera coordinates with world coordinates? I would really appreciate your help.

**Comment by lyumingzhi** [comment]
Great work! i want to know the camera parameters too, because i want to do visualization

**Comment by 3dpose** [comment]
Thanks for your interest in our work!

In Figure 1, we first estimate the camera-centric skeletons, and then rotate up the camera from 0 to 25 degrees for visualization purpose. In this paper, 3D poses are estimated in camera-centric way, not in world coordinates.

**Comment by nicolasugrinovic** [comment]
How about figure 5. Do you estimate camera intrinsics to later project the 3D joints?

Thanks
