### ISSUE TITLE
Dropbox not working

### ISSUE THREAD

**Issue by psuu0001** [3dpose/3D-Multi-Person-Pose#6]
Hi, very appreciate for your great work. Could you please share other links to download the pretrained model? cause the dropbox seems to be unconnected.

**Comment by 3dpose** [comment]
Thanks for your interest in our work. 

Just downloaded the [pre-trained models](https://github.com/3dpose/3D-Multi-Person-Pose#pre-trained-models) and there is no problem. Can you try again?

**Comment by Akshaypatil7** [comment]
> Hi, very appreciate for your great work. Could you please share other links to download the pretrained model? cause the dropbox seems to be unconnected.

Hi, Have you found the pre trained models
